name: Build Demo Web
description: Build Demo on web
author: Luo3House
inputs:
  base:
    description: Base href params for build command
    required: false
    default: '/'
  workdir:
    description: working-directory
    default: '.'
runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.10'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        architecture: x64
    - name: Install Pub
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: flutter pub get
    - name: Build web with base href
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: flutter build web --base-href=${{ inputs.base }}
