name: Build Docs
description: Build Docs
author: Luo3House
inputs:
  base:
    description: Base url
    required: false
    default: '/'
  demo_base:
    description: Demo base url
    required: false
    default: '/'
runs:
  using: composite
  steps:
    - name: Setup Pnpm
      shell: bash
      run: |
        node -v
        npm -v
        npm -g i pnpm
        pnpm -v
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.10'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        architecture: x64
    - name: Install Dependencies For Workspace
      shell: bash
      run: pnpm i
    - name: Build Docs
      shell: bash
      run: VITE_DEMO_VIEW_BASEURL=${{ inputs.demo_base }} pnpm --filter=docs build --base=${{ inputs.base }}
