name: Build Test

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prerequisite
        run: echo ${{ github.event.pull_request.head.sha }}
      - name: Build Demo Web
        uses: ./.github/actions/build-demo-web
        with:
          workdir: demo/
      - name: Build Docs
        uses: ./.github/actions/build-docs
