name: Deploy Demo

on:
  push:
    branches: ['main']

env:
  DOCS_BASE: /flutter_vant/
  DEMO_BASE: /flutter_vant/demo/

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Build Demo Web
        uses: ./.github/actions/build-demo-web
        with:
          base: ${DEMO_BASE}
          workdir: demo/
      - name: Build Docs
        uses: ./.github/actions/build-docs
        with:
          base: ${DOCS_BASE}
          demo_base: ${DEMO_BASE}
      - name: Merge Dist
        shell: bash
        run: cp -r ./demo/build/web ./docs/.vitepress/dist/demo
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: docs/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Download Build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: '.'
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1
